    public final util.h.xy.ct.mf \u037a() throws java.io.IOException
    {
        java.lang.Throwable $r3;
        util.h.xy.ct.rg $r2;
        util.h.xy.ct.n r0;
        util.h.xy.ct.mf $r1;
        java.lang.NullPointerException r4;
        byte $b2;
        int $i0, $i1;
        boolean $z0;

        r0 := @this: util.h.xy.ct.n;

        $i0 = <util.h.xy.ct.n: int \u02cb>;

        $i0 = $i0 + 9;

        $i0 = $i0 % 128;

        <util.h.xy.ct.n: int \u02ce> = $i0;

        $r2 = r0.<util.h.xy.ct.n: util.h.xy.ct.rg \u02cf>;

        $z0 = r0.<util.h.xy.ct.n: boolean \u141d>;

        $i0 = r0.<util.h.xy.ct.n: int \u02ca>;

        $r1 = virtualinvoke $r2.<util.h.xy.ct.rg: util.h.xy.ct.mf \u02ca(boolean,int)>($z0, $i0);

        $i0 = <util.h.xy.ct.n: int \u02ce>;

        $i0 = $i0 + 69;

        $i1 = $i0 % 128;

        <util.h.xy.ct.n: int \u02cb> = $i1;

        $i0 = $i0 % 2;

        if $i0 == 0 goto label1;

        $b2 = 67;

        goto label2;

     label1:
        $b2 = 99;

     label2:
        if $b2 == 67 goto label3;

        return $r1;

     label3:
        r4 = new java.lang.NullPointerException;

        specialinvoke r4.<java.lang.NullPointerException: void <init>(java.lang.String)>("This statement would have triggered an Exception: specialinvoke $u1#14.<java.lang.Object: int hashCode()>()");

        throw r4;

     label4:
        $r3 := @caughtexception;

        throw $r3;

        catch java.lang.Throwable from label3 to label4 with label4;
    }
